AWSTemplateFormatVersion: "2010-09-09"

Resources:

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !ImportValue burninator-service:HTTPTarget
          Type: forward
      LoadBalancerArn: !ImportValue burninator-compute:LoadBalancerArn
      Port: 80
      Protocol: HTTP

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !ImportValue burninator-service:HTTPTarget
          Type: forward
      LoadBalancerArn: !ImportValue burninator-compute:LoadBalancerArn
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-west-1:123972995618:certificate/103047ed-5260-4791-942a-c0128cbb4d65


  CertificateValidation:
    Type: AWS::Route53::RecordSet
    Properties :
      HostedZoneName : tl.cjpowered.com.
      Name: _28dc5e9c805bdf71c161f49deb980876.burninator.tl.cjpowered.com.
      Type: CNAME
      TTL: 900
      ResourceRecords:
        - _bf81a436d18b546440e666123aa0cf23.ltfvzjuylp.acm-validations.aws

  Domain:
    Type: AWS::Route53::RecordSet
    Properties :
      HostedZoneName : tl.cjpowered.com.
      Name: burninator.tl.cjpowered.com.
      Type: A
      AliasTarget:
        HostedZoneId: !ImportValue burninator-compute:LoadBalancerCanonicalHostedZoneID
        DNSName: !ImportValue burninator-compute:LoadBalancerDNSName

Outputs:
  URL:
    Value: http://${Domain}
