AWSTemplateFormatVersion: '2010-09-09'

Resources:
  BackupStore:
    Type: AWS::S3::Bucket
    Properties:
        VersioningConfiguration:
          Status: Enabled
        LifecycleConfiguration:
          Rules:
            - Id: clean
              Status: Enabled
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 2
            - Id: archive
              Status: Enabled
              NoncurrentVersionTransitions:
                - StorageClass : GLACIER
                  TransitionInDays : 10
            - Id: remove
              Status: Enabled
              NoncurrentVersionExpirationInDays: 60

  PutToBackupStorePolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                  Resource:
                    - !Sub ${BackupStore.Arn}/*

  DataVolume:
    Type: AWS::EFS::FileSystem

  LeftDataVolumeTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId : !Ref DataVolume
      SecurityGroups :
        - !ImportValue network-AttachedNetworkDefaultSecurityGroup
      SubnetId : !ImportValue network-AttachedNetworkLeftSubnet

  RightDataVolumeTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId : !Ref DataVolume
      SecurityGroups :
        - !ImportValue network-AttachedNetworkDefaultSecurityGroup
      SubnetId : !ImportValue network-AttachedNetworkRightSubnet


Outputs:
  BackupStore:
    Value: !Ref BackupStore
    Export:
      Name: !Sub ${AWS::StackName}:BackupStore
  DataVolume:
    Value: !Ref DataVolume
    Export:
      Name: !Sub ${AWS::StackName}:DataVolume
  PutToBackupStorePolicyArn:
    Value: !Ref PutToBackupStorePolicy
    Export:
      Name: !Sub ${AWS::StackName}:PutToBackupStorePolicyArn
  LeftDataVolumeTarget:
    Value: !Ref LeftDataVolumeTarget
    Export:
      Name: !Sub ${AWS::StackName}:LeftDataVolumeTarget
  RightDataVolumeTarget:
    Value: !Ref RightDataVolumeTarget
    Export:
      Name: !Sub ${AWS::StackName}:RightDataVolumeTarget


