AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Datastore:
    Type: AWS::S3::Bucket

  ReadWriteDataPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - s3:DeleteObject
                    - s3:DeleteObjectVersion
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:ListBucketMultipartUploads
                    - s3:ListBucketVersions
                    - s3:ListMultipartUploadParts
                    - s3:PutObject
                  Resource:
                    - !Sub ${Datastore.Arn}/*

  DataVolume:
    Type: AWS::EFS::FileSystem

  LeftDataVolumeTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId : !Ref DataVolume
      SecurityGroups :
        - !ImportValue network-AttachedNetworkDefaultSecurityGroup
      SubnetId : !ImportValue network-AttachedNetworkLeftSubnet

  RightDataVolumeTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId : !Ref DataVolume
      SecurityGroups :
        - !ImportValue network-AttachedNetworkDefaultSecurityGroup
      SubnetId : !ImportValue network-AttachedNetworkRightSubnet


Outputs:
  Datastore:
    Value: !Ref Datastore
    Export:
      Name: !Sub ${AWS::StackName}:Datastore
  ReadWritePolicyArn:
    Value: !Ref ReadWriteDataPolicy
    Export:
      Name: !Sub ${AWS::StackName}:ReadWriteDataPolicyArn
  LeftDataVolumeTarget:
    Value: !Ref LeftDataVolumeTarget
    Export:
      Name: !Sub ${AWS::StackName}:LeftDataVolumeTarget
  RightDataVolumeTarget:
    Value: !Ref RightDataVolumeTarget
    Export:
      Name: !Sub ${AWS::StackName}:RightDataVolumeTarget


